"""empty message

Revision ID: 2f94077ac6c5
Revises: 418102435a6d
Create Date: 2025-06-12 23:20:46.992180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f94077ac6c5'
down_revision = '418102435a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_text', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments', schema=None) as batch_op:
        batch_op.drop_column('comment_text')

    # ### end Alembic commands ###
