"""empty message

Revision ID: 418102435a6d
Revises: ae02743c8eb6
Create Date: 2025-06-12 23:11:38.471074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418102435a6d'
down_revision = 'ae02743c8eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.Enum('IMAGE', 'VIDEO', 'TEXT', name='posttype'), nullable=False),
    sa.Column('post_url', sa.String(length=120), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['Profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['Profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Comments')
    op.drop_table('Post')
    op.drop_table('Follow')
    # ### end Alembic commands ###
